### ISSUE TITLE
Application for Hack4Impact McGill

### ISSUE THREAD

**Issue by MikaVohl** [1Password/for-open-source#1027]
### Account URL

hack4impactmcgill.1password.com

### Non-commercial confirmation

- [X] No, this account won't be used for commercial activity

### Team application

- [X] Yes, this application is for a team

### Event application

- [ ] Yes, this application is for an event

### Project name

Hack4Impact McGill

### Short description

Hack4Impact McGill is a student-led collective that specializes in providing software solutions for non-profit organization. At Hack4Impact McGill, we have 3 teams, all working on different year-long projects that will help the community. Our website, along with many other projects is open-source and our collective is non-profit.

### Number of team members/core contributors

30

### Homepage URL

https://mcgill.hack4impact.org/

### Repository URL

https://github.com/hack4impact-mcgill/mcgill.hack4impact.org

### License type

MIT

### License URL

https://github.com/hack4impact-mcgill/mcgill.hack4impact.org?tab=MIT-1-ov-file

### Age confirmation

- [X] Yes, this project is at least 30 days old

### Name

Mika Vohl

### Email

mika@hack4impact.org

### Project role

Organizer or Admin

### Profile or website

https://mikavohl.ca/

### Can we contact you?

- [ ] Yes, you may contact me

**Comment by jodyheavener** [comment]
Hey @MikaVohl, thanks for your application! Love to see a McGill group in here. If I'm understanding correctly, it looks like the purpose of this group is more about providing software solutions for non-profits, and while the website and various projects may be open source, the 1Password account isn't strictly used to further these open source projects specifically. If that is correct, and since you are a non-profit yourselves, I'm wondering if our [1Password for Non-Profits](https://1password.com/for-non-profits/) program might be a better fit, since we typically try to reserve space in this program for the furtherance of open source software. Would you agree with that?

**Comment by MikaVohl** [comment]
Hey @jodyheavener,

The software we develop does actually involve contributions from outside of the organization. Our projects are open source and have relied on external collaborators for more complex features. This collaboration has been mostly from students at different schools and outside of our organization, but we want to improve the process with collaborators from anywhere. To enable this, we feel we need a way to securely share credentials and deal with authentication codes without relying on members' personal devices or email addresses. For this reason, we wanted to reach out to 1Password since some of our members have used the service before and are impressed.

Overall, I do feel like we would fall under the Open Source category more than the Non-Profit category. We have external collaboration on our open source projects, and are hoping to use 1Password to further this collaboration.

Hope this makes sense :)

**Comment by jodyheavener** [comment]
Hey @MikaVohl, thanks for your response. That sounds reasonable to me! Happy hacking :)
