### ISSUE TITLE
Application for App Inventor Foundation

### ISSUE THREAD

**Issue by mark-friedman** [1Password/for-open-source#1031]
### Account URL

https://appinventorfoundation.1password.com/

### Non-commercial confirmation

- [X] No, this account won't be used for commercial activity

### Team application

- [X] Yes, this application is for a team

### Event application

- [ ] Yes, this application is for an event

### Project name

App Inventor

### Short description

App Inventor was founded in 2007 with the vision of enabling anyone—including those who may not think of themselves as coders—to create mobile apps for real, effective change in their communities.  The App Inventor Foundation was established to support the ongoing development of App Inventor and its users.

### Number of team members/core contributors

10

### Homepage URL

https://appinventorfoundation.org

### Repository URL

https://github.com/mit-cml/appinventor-sources

### License type

Apache-2.0

### License URL

https://github.com/mit-cml/appinventor-sources?tab=Apache-2.0-1-ov-file#readme

### Age confirmation

- [X] Yes, this project is at least 30 days old

### Name

Mark Friedman

### Email

mark@appinventorfoundation.org

### Project role

Founder or Owner

### Profile or website

https://www.linkedin.com/in/marksfriedman/

### Can we contact you?

- [X] Yes, you may contact me

**Comment by jodyheavener** [comment]
Hey @mark-friedman, thanks for your application! This looks like a really amazing initiative, and it's great that you want to use 1Password to help secure it. That said, we typically reserve this program for individuals and teams working on open source software, and while App Inventor Foundation appears to have a mission of enabling others to create software it doesn't appear to quite fit these requirements. We might still be able to help, though! Since you're a non-profit I'd recommend checking out [1Password for Non-Profits](https://1password.com/for-non-profits/), as they may be able to set something up for you depending on your situation. Let me know if you have any questions, and if you feel I've missed something I'd be more than happy to take another look!

**Comment by mark-friedman** [comment]
@jodyheavener It's a little complicated because we are in the process of moving support and development of the App Inventor open source code (i.e. https://github.com/mit-cml/appinventor-sources) from MIT (and the mit-cml GitHub org) to the App Inventor Foundation.  That transition is not yet complete.  You can see that I am also founder of the App Inventor project as well as a maintainer and major contributor to the open source project.  You can also see that other members of the foundation team are also in the MIT App Inventor group and will be among the folks using the foundation's 1Password account.

**Comment by jodyheavener** [comment]
That sounds reasonable to me. Thanks for clarifying!

**Comment by mark-friedman** [comment]
@jodyheavener, Around the time of your last message we received an email from 1Password saying that our subscription has ended and that our account is now frozen.  Is that to be expected?
